server:
  port: 8080
  servlet:
    context-path: /labeasy
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/pages/
      suffix: .jsp
  profiles:
    active: local
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/labeasy
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles: local
      