server:
  port: 8087
  servlet:
    context-path: /labeasy
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/pages/
      suffix: .jsp
  profiles:
    active: local
---
spring: 
  liquibase:
    change-log:  classpath:/db/changelog/change-db-log.xml
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    tomcat: 
      default-auto-commit: true
      initial-size: 20
      max-active: 50
      max-idle: 15
      max-wait: 20000
    url: "jdbc:mysql://localhost:3306/labeasy"
    username: root
  jpa: 
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        enable_lazy_load_no_trans: true
        format_sql: false
    show-sql: false
  mail: 
    default-encoding: UTF-8
    host: smtp.gmail.com
    password:  
    port: 587
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
    protocol: smtp
    test-connection: false
    username: Nasruddin.nk44@gmail.com
  quartz:
    jdbc:
      schema: classpath:quartz_tables.sql
    job-store-type: jdbc
    properties:
     org:
      quartz:
        threadPool:
          threadCount: 5
  profiles: local
aws:
  access_key_id: AKIA27B3VZFOM75WGINU 
  s3:
    bucket: labeasy-invoice
    endpointUrl: http://labeasy-invoice.s3-website-us-east-1.amazonaws.com
  secret_access_key: Ul3ljSN8wchbGaraOruuGhbO5SjuUTKrSERUv0or
  
