server:
  port: 8087
  servlet:
    context-path: /labeasy
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/pages/
      suffix: .jsp
  profiles:
    active: local
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/labeasy
    username: root    tomcat:      default-auto-commit: true
      initial-size: 20
      max-active: 50
      max-idle: 15
      max-wait: 20000 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles: local
  